import org.jetbrains.compose.desktop.application.dsl.TargetFormat
import org.jetbrains.kotlin.gradle.dsl.JvmTarget

plugins {
    alias(libs.plugins.kotlinMultiplatform)
    alias(libs.plugins.androidApplication)
    alias(libs.plugins.composeMultiplatform)
    alias(libs.plugins.composeCompiler)
    alias(libs.plugins.composeHotReload)
    alias(libs.plugins.ksp)
    alias(libs.plugins.androidx.room)
}

val generateSupportedLocales = tasks.register("generateSupportedLocales") {
    val outputDir = layout.buildDirectory.dir("generated/kotlin/locale")
    val resourceDirs = listOf(layout.projectDirectory.dir("src/commonMain/composeResources").asFile)

    inputs.files(resourceDirs)
    outputs.dir(outputDir)

    doLast {
        fun parseLocaleFromValuesDirName(dirName: String): String? {
            if (dirName == "values") return null
            val rest = dirName.removePrefix("values-").takeIf { it != dirName } ?: return null

            val normalizedRest = if (rest.startsWith("b+")) {
                rest.removePrefix("b+").replace("+", "-")
            } else {
                rest
            }

            val parts = normalizedRest.split('-').filter { it.isNotEmpty() }
            if (parts.isEmpty()) return null

            val firstPart = parts[0].lowercase()
            if (!firstPart.matches(Regex("^[a-z]{2,3}$"))) return null

            var script: String? = null
            var region: String? = null

            for (i in 1 until parts.size) {
                val part = parts[i]
                if (part.matches(Regex("^(land|port|night|notnight|ldpi|mdpi|hdpi|xhdpi|v\\d+)\$"))) {
                    break
                }

                val cleanPart = if (part.length == 3 && part.startsWith("r") && part[1].isLetter() && part[2].isLetter()) {
                    part.substring(1)
                } else {
                    part
                }

                if (cleanPart.length == 4 && cleanPart.all { it.isLetter() }) {
                    script = cleanPart.lowercase().replaceFirstChar { if (it.isLowerCase()) it.titlecase() else it.toString() }
                } else if ((cleanPart.length == 2 && cleanPart.all { it.isLetter() }) || (cleanPart.length == 3 && cleanPart.all { it.isDigit() })) {
                    region = if (cleanPart.all { it.isDigit() }) cleanPart else cleanPart.uppercase()
                }
            }

            return buildString {
                append(firstPart)
                if (script != null) {
                    append('-')
                    append(script)
                }
                if (region != null) {
                    append('-')
                    append(region)
                }
            }
        }

        val locales = sortedSetOf<String>()
        resourceDirs.forEach { root ->
            root.listFiles()?.filter {
                it.isDirectory && !it.name.startsWith(".")
            }?.forEach { f ->
                parseLocaleFromValuesDirName(f.name)?.let { locales.add(it) }
            }
        }

        val outRoot = outputDir.get().asFile
        val pkgDir = File(outRoot, "com/iam2kabhishek/notey/locale")
        pkgDir.mkdirs()
        val body = buildString {
            appendLine("/* Generated by generateSupportedLocales task — do not edit. */")
            appendLine("package com.iam2kabhishek.notey.locale")
            appendLine()
            appendLine("object SupportedLocales {")
            appendLine("    val supported: Set<String> = setOf(")
            locales.forEach { tag ->
                val esc = tag.replace("\\", "\\\\").replace("\"", "\\\"")
                appendLine("        \"$esc\",")
            }
            appendLine("    )")
            appendLine("}")
        }
        File(pkgDir, "SupportedLocales.kt").writeText(body)
    }
}

kotlin {
    androidTarget {
        compilerOptions {
            jvmTarget.set(JvmTarget.JVM_11)
        }
    }
    
    listOf(
        iosArm64(),
        iosSimulatorArm64()
    ).forEach { iosTarget ->
        iosTarget.binaries.framework {
            baseName = "ComposeApp"
            isStatic = true
        }
    }
    
    jvm()
    
    sourceSets {
        commonMain {
            kotlin.srcDir(generateSupportedLocales)
        }
        androidMain.dependencies {
            implementation(libs.compose.uiToolingPreview)
            implementation(libs.androidx.activity.compose)
            implementation(libs.androidx.room.ktx)
        }
        commonMain.dependencies {
            implementation(libs.compose.runtime)
            implementation(libs.compose.foundation)
            implementation(libs.compose.material3)
            implementation(compose.materialIconsExtended)
            implementation(libs.compose.ui)
            implementation(libs.compose.components.resources)
            implementation(libs.compose.uiToolingPreview)
            implementation(libs.androidx.lifecycle.viewmodelCompose)
            implementation(libs.androidx.lifecycle.runtimeCompose)
            implementation(libs.androidx.room.runtime)
            implementation(libs.androidx.sqlite.bundled)
        }
        commonTest.dependencies {
            implementation(libs.kotlin.test)
        }
        jvmMain.dependencies {
            implementation(compose.desktop.currentOs)
            implementation(libs.kotlinx.coroutinesSwing)
            implementation("net.java.dev.jna:jna:5.17.0")
            implementation("net.java.dev.jna:jna-platform:5.17.0")
        }
    }
}

android {
    namespace = "com.iam2kabhishek.notey"
    compileSdk = libs.versions.android.compileSdk.get().toInt()

    defaultConfig {
        applicationId = "com.iam2kabhishek.notey"
        minSdk = libs.versions.android.minSdk.get().toInt()
        targetSdk = libs.versions.android.targetSdk.get().toInt()
        versionCode = 1
        versionName = "1.0"
    }
    packaging {
        resources {
            excludes += "/META-INF/{AL2.0,LGPL2.1}"
        }
    }
    buildTypes {
        getByName("release") {
            isMinifyEnabled = false
        }
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11
    }
}

ksp { }

room {
    schemaDirectory("$projectDir/schemas")
}

dependencies {
    add("kspAndroid", libs.androidx.room.compiler)
    add("kspIosSimulatorArm64", libs.androidx.room.compiler)
    add("kspIosArm64", libs.androidx.room.compiler)
    add("kspJvm", libs.androidx.room.compiler)
    debugImplementation(libs.compose.uiTooling)
}

compose.desktop {
    application {
        mainClass = "com.iam2kabhishek.notey.MainKt"

        nativeDistributions {
            targetFormats(TargetFormat.Dmg, TargetFormat.Msi, TargetFormat.Deb)
            packageName = "com.iam2kabhishek.notey"
            packageVersion = "1.0.0"
        }
    }
}

tasks.register("checkAll") {
    group = "verification"
    description = "Runs KMP compile checks and Android lint"
    dependsOn(
        "compileKotlinJvm",
        "compileKotlinIosSimulatorArm64",
        "assembleDebug",
        "lintDebug"
    )
}
